on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Get Pokemon name
        uses: ./
        id: pokemon
        with:
          pokemon_id: 150
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"